name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: deployment
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd ./pla_backend
          git pull origin main
          source ./.venv/bin/activate
          pip install -r requirements.txt
          mkdir -p logging
          python manage.py migrate
          sudo systemctl restart django
        host: '42.194.158.76'
        user: pla_backend
        port: 22
        key: ${{ secrets.SSH_PRIVATE_KEY }}
